### ISSUE TITLE
timeslot_start=gte_now bringing in unexpected results

### ISSUE THREAD

**Issue by MikeiLL** [mobilizeamerica/api#19]
Hi friends.

[This url](https://events.mobilizeamerica.io/api/v1/events?organization_id=205&gte_now&per_page=10), I would expect to bring in results that are similar to the ones on [this page](https://events.mobilizeamerica.io/nydems/). It's pulling in every event we've posted.

[This url](https://events.mobilizeamerica.io/api/v1/events?organization_id=205&timeslot_start=gte_1544064943&per_page=10) with `timeslot_start` of now(ish) brings in no events.

Is our Mobilize page pulling from a different set of data, possibly associated with a different `organization_id`?

**Comment by kylehg** [comment]
Hey @MikeiLL:

The first API URL is not filtering on time (you need `timeslot_start=gte_now`) so it's showing all events _created by_ NY Dems over all time.

The second API URL shows all events _created by_ NY Dems in the future, which there are none.

The reason the NY dems feed has events is because they're promoting other orgs. If you want an API call that mirrors the feed (i.e., includes promoted events), use [List organization events](https://github.com/mobilizeamerica/api#list-organization-events)
